<?
	if ( !$ADMIN_FLAG )
		die("No Access");

	$query="SELECT CONCAT(first_name,' ',last_name) as name, SUM( quantity ) AS quantity , SUM( quantity * sell_price ) AS bought,
		COUNT(DISTINCT o.order_number) AS orders
		FROM
		   (
			(
			customers b INNER JOIN orders o
			ON b.username=o.username
			)
		   	INNER JOIN contains c 
			ON o.order_number = c.order_number
		   )
		   INNER  JOIN dvd d 
		   ON d.barcode = c.barcode
		GROUP BY b.username ORDER BY bought DESC
		LIMIT 5";
	$results = mysqlQuery($query);
?>
<h2>Best Customers</h2>
<b>Date:</b> <? print(date("d/m/Y H:m:i"));?><br>
<table cellspacing="0" cellpadding="4" bordercolor="black" border="2" bgcolor="orange">
	<tr><td>
		<table cellpadding="0" cellspacing="0" border="0" class="listing">
	<tr><th><br>Name</th><th>Orders<br>Placed&nbsp;</th><th>&nbsp;DVDs<br>Purchased&nbsp;</th>
	<th><br>&nbsp;Spent&nbsp;</th></tr>
<?
	$total = 0;
	foreach($results as $i=>$item)
	{
		if ( $i % 2 == 0 )
			$bgcolor="#ECECEC";
		else
			$bgcolor="";
		print("<tr bgcolor=\"$bgcolor\"><td><b>".($i+1)."</b>.&nbsp;".$item['name']."</td>".
		"<td align=\"center\">".$item['orders']."</td>".
		"<td align=\"center\">".$item['quantity']."</td><td align=\"center\">$".
		$item['bought']."</td></tr>");
		$total += $item['bought'];
	}
?>
</table>
</td></tr></table>
Total Revenue generated by 5 best customers: <b>$<? print($total); ?></b>
<div class="help">Note: We are aware of the naivity of this report - as this report does not take into account
the fact that the DVD titles can change price. This would be solved by adding an "sold price" attribute in the
"contains" entity. We did not change this because we have tried to keep this project simplified to a certain level.</div>
<!-- footer -->
</td></tr></table>