<?
	if ( !$ADMIN_FLAG )
		die("No Access");

	$query="SELECT 	title, stock_avail, (sell_price-cost) AS profit, sum(c.quantity) as sold, ".
		"sum(s.quantity) as baskets FROM (dvd d LEFT OUTER JOIN contains c ON d.barcode=c.barcode".
		") LEFT OUTER JOIN shopping_trolley s ON d.barcode = s.barcode GROUP BY profit ".
		"ORDER BY profit DESC LIMIT 5";
	$results = mysqlQuery($query);
?>
<h2>Top 5 Profitable DVDs</h2>
<b>Date:</b> <? print(date("d/m/Y H:m:i"));?><br>
<table cellspacing="0" cellpadding="4" bordercolor="black" border="2" bgcolor="orange">
	<tr><td>
		<table cellpadding="0" cellspacing="0" border="0" class="listing">
	<tr><th>Title</th><th>In baskets&nbsp;</th><th>&nbsp;Profit / unit&nbsp;</th>
	<th>&nbsp;Dispatches&nbsp;</th><th>&nbsp;Revenue</th></tr>
<?
	$total = 0;
	foreach($results as $i=>$item)
	{
		if ( $i % 2 == 0 )
			$bgcolor="#ECECEC";
		else
			$bgcolor="";
		print("<tr bgcolor=\"$bgcolor\"><td><b>".($i+1)."</b>.&nbsp;".$item['title']."</td>".
		"<td align=\"center\">".$item['baskets']."</td>".
		"<td align=\"center\">$".$item['profit']."</td><td align=\"center\">".
		$item['sold']."</td><td align=\"center\">$".($item['sold']*$item['profit']).
		"</td></tr>");
		$total += ($item['sold']*$item['profit']);
	}
?>
</table>
</td></tr></table>
Total Revenue generated by top profitable DVDS: <b>$<? print($total); ?></b>
<!-- footer -->
</td></tr></table>